version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:484941465042:task-definition/teste-ecs-poc:1"
        LoadBalancerInfo:
          ContainerName: ecs-poc-pipeline
          ContainerPort: 80