version: 0.2

phases:
  install:
      runtime-versions:
          docker: 18

  build:
    commands:
      - ls -la
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ./teste:latest .

artifacts:
    files:
        - imagedefinitions.json
